 global class ProductData{

    public String id;
    public Decimal listPrice;
    public Decimal unitPrice;

/*
static testMethod void testParse() {
    String jsonString = '[{"productId": "pid1","listPrice":10,"unitPrice":5}, {"productId": "pid2","listPrice":10,"unitPrice":5}, {"productId": "pid3","listPrice":10,"unitPrice":5}]';
    fromJSON obj = parse(json);
    System.assert(obj != null);
}*/
}